In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import keras
import tensorflow as tf

In [23]:
dataset = pd.read_csv('training-ds.csv', encoding='utf-8')
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>

In [24]:
dataset[:10]

,Tipo de Red,Estudiante de Tecnología,Nivel de Educación,Vive en Ciudad,Tipo de Instituto,Edad,Dispositivo,Tipo de Internet,Situación Financiera,Género,Duración de la Clase,Nivel de Adaptación
0,3G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Media,Masculino,03-Jun,Bajo
1,3G,No,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Femenino,01-Mar,Moderado
2,3G,Si,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,01-Mar,Bajo
3,3G,Si,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
4,4G,Si,Universidad,Si,Privado,21-25,Computadora,Wifi,Buena,Masculino,01-Mar,Alto
5,3G,No,Escuela,No,Público,Nov-15,Smartphone,Compra Megas,Media,Masculino,0,Bajo
6,4G,Si,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
7,3G,No,Escuela,Si,Privado,Nov-15,Smartphone,Compra Megas,Media,Masculino,01-Mar,Moderado
8,4G,No,Universidad,Si,Privado,21-25,Smartphone,Compra Megas,Mala,Masculino,01-Mar,Alto
9,4G,No,Escuela,Si,Público,16-20,Smartphone,Wifi,Media,Masculino,01-Mar,Moderado

In [25]:
#dummies = pd.get_dummies(dataset['Tipo de Red'], drop_first=True)  
# drop_first se usa para eliminar una columna (categoria), ya que si no corresponde a las otras automaticamente es esa.
# reduces una columan innecesaria
dataset_one_hot_encoded = pd.get_dummies(dataset)  
dataset_one_hot_encoded

,Tipo de Red_2G,Tipo de Red_3G,Tipo de Red_4G,Estudiante de Tecnología_No,Estudiante de Tecnología_Si,Nivel de Educación_Colegio,Nivel de Educación_Escuela,Nivel de Educación_Universidad,Vive en Ciudad_No,Vive en Ciudad_Si,...,Situación Financiera_Mala,Situación Financiera_Media,Género_Femenino,Género_Masculino,Duración de la Clase_0,Duración de la Clase_01-Mar,Duración de la Clase_03-Jun,Nivel de Adaptación_Alto,Nivel de Adaptación_Bajo,Nivel de Adaptación_Moderado
0,0,1,0,0,1,0,0,1,0,1,...,0,1,0,1,0,0,1,0,1,0
1,0,1,0,1,0,0,1,0,0,1,...,0,1,1,0,0,1,0,0,0,1
2,0,1,0,0,1,0,0,1,0,1,...,1,0,0,1,0,1,0,0,1,0
3,0,1,0,0,1,0,1,0,0,1,...,0,1,0,1,0,1,0,0,0,1
4,0,0,1,0,1,0,0,1,0,1,...,0,0,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,0,1,0,1,0,0,0,1,0,1,...,0,1,0,1,0,1,0,0,0,1
960,0,1,0,1,0,0,1,0,0,1,...,0,1,1,0,0,1,0,0,0,1
961,0,0,1,1,0,0,0,1,0,1,...,0,1,0,1,1,0,0,0,1,0
962,0,1,0,1,0,0,0,1,0,1,...,0,1,0,1,0,1,0,0,0,1
963,0,0,1,1,0,0,1,0,0,1,...,0,1,1,0,0,1,0,0,0,1

In [26]:
X = dataset_one_hot_encoded.iloc[:,:31]
X

,Tipo de Red_2G,Tipo de Red_3G,Tipo de Red_4G,Estudiante de Tecnología_No,Estudiante de Tecnología_Si,Nivel de Educación_Colegio,Nivel de Educación_Escuela,Nivel de Educación_Universidad,Vive en Ciudad_No,Vive en Ciudad_Si,...,Tipo de Internet_Compra Megas,Tipo de Internet_Wifi,Situación Financiera_Buena,Situación Financiera_Mala,Situación Financiera_Media,Género_Femenino,Género_Masculino,Duración de la Clase_0,Duración de la Clase_01-Mar,Duración de la Clase_03-Jun
0,0,1,0,0,1,0,0,1,0,1,...,0,1,0,0,1,0,1,0,0,1
1,0,1,0,1,0,0,1,0,0,1,...,1,0,0,0,1,1,0,0,1,0
2,0,1,0,0,1,0,0,1,0,1,...,1,0,0,1,0,0,1,0,1,0
3,0,1,0,0,1,0,1,0,0,1,...,1,0,0,0,1,0,1,0,1,0
4,0,0,1,0,1,0,0,1,0,1,...,0,1,1,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,0,1,0,1,0,0,0,1,0,1,...,1,0,0,0,1,0,1,0,1,0
960,0,1,0,1,0,0,1,0,0,1,...,1,0,0,0,1,1,0,0,1,0
961,0,0,1,1,0,0,0,1,0,1,...,1,0,0,0,1,0,1,1,0,0
962,0,1,0,1,0,0,0,1,0,1,...,1,0,0,0,1,0,1,0,1,0
963,0,0,1,1,0,0,1,0,0,1,...,1,0,0,0,1,1,0,0,1,0

In [27]:
y = dataset_one_hot_encoded.iloc[:,31:]
y

,Nivel de Adaptación_Alto,Nivel de Adaptación_Bajo,Nivel de Adaptación_Moderado
0,0,1,0
1,0,0,1
2,0,1,0
3,0,0,1
4,1,0,0
...,...,...,...
959,0,0,1
960,0,0,1
961,0,1,0
962,0,0,1
963,0,0,1

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(771, 31) (771, 3)
(193, 31) (193, 3)

In [29]:
# import sklearn
# sklearn.svm.SVC(*, 
#     C=1.0,                          # The regularization parameter
#     kernel='rbf',                   # The kernel type used 
#     degree=3,                       # Degree of polynomial function 
#     gamma='scale',                  # The kernel coefficient
#     coef0=0.0,                      # If kernel = 'poly'/'sigmoid'
#     shrinking=True,                 # To use shrinking heuristic
#     probability=False,              # Enable probability estimates
#     tol=0.001,                      # Stopping crierion
#     cache_size=200,                 # Size of kernel cache
#     class_weight=None,              # The weight of each class
#     verbose=False,                  # Enable verbose output
#     max_iter=- 1,                   # Hard limit on iterations
#     decision_function_shape='ovr',  # One-vs-rest or one-vs-one
#     break_ties=False,               # How to handle breaking ties
#     random_state=None               # Random state of the model
# )

In [30]:
print(type(y_train), type(y_test))
y_train = y_train.apply(lambda x: x.argmax(), axis=1).values
y_train.shape
y_test = y_test.apply(lambda x: x.argmax(), axis=1).values
y_test.shape

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>

(193,)

In [31]:
from sklearn.svm import SVC
clf = SVC(kernel='rbf')
clf.fit(X_train, y_train)

SVC()

In [32]:
predictions = clf.predict(X_test)
print(predictions[:5])

[2 2 1 1 1]

In [33]:
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

0.8352788586251622
0.7668393782383419

In [ ]:
#solo con numeros o tambien con one hot encoding???
# explic